import { useTranslations } from "next-intl";


export default function productsTable() {
	
	const t = useTranslations("products")


	const productsData = [
		{
		  id: 1,
		  name: "Smartphone X",
		  sku_code: "SKU1001",
		  wholesale_price: "120.50 USD",
		  categories: "Electronics",
		  manufacturing: "International",
		  in_progress: 150,
		  returned: 5,
		  with_shipping_companies: 3200,
		  sold_pieces: 1200,
		  on_shelf: 500,
		  status: "Available",
		  action: "",
		},
		{
		  id: 2,
		  name: "Wireless Headphones",
		  sku_code: "SKU1002",
		  wholesale_price: "75.99 USD",
		  categories: "Electronics",
		  manufacturing: "Local",
		  in_progress: 100,
		  returned: 8,
		  with_shipping_companies: 2500,
		  sold_pieces: 900,
		  on_shelf: 400,
		  status: "Available",
		  action: "",
		},
		{
		  id: 3,
		  name: "Running Shoes",
		  sku_code: "SKU1003",
		  wholesale_price: "60.00 USD",
		  categories: "Sports",
		  manufacturing: "International",
		  in_progress: 80,
		  returned: 3,
		  with_shipping_companies: 2800,
		  sold_pieces: 700,
		  on_shelf: 300,
		  status: "Active",
		  action: "",
		},
		{
		  id: 4,
		  name: "Gaming Mouse",
		  sku_code: "SKU1004",
		  wholesale_price: "45.25 USD",
		  categories: "Electronics",
		  manufacturing: "Local",
		  in_progress: 120,
		  returned: 6,
		  with_shipping_companies: 3100,
		  sold_pieces: 850,
		  on_shelf: 450,
		  status: "Available",
		  action: "",
		},
		{
		  id: 5,
		  name: "Leather Jacket",
		  sku_code: "SKU1005",
		  wholesale_price: "150.00 USD",
		  categories: "Clothing",
		  manufacturing: "International",
		  in_progress: 90,
		  returned: 2,
		  with_shipping_companies: 2200,
		  sold_pieces: 600,
		  on_shelf: 250,
		  status: "Pending",
		  action: "",
		},
		{
		  id: 6,
		  name: "Bluetooth Speaker",
		  sku_code: "SKU1006",
		  wholesale_price: "95.75 USD",
		  categories: "Electronics",
		  manufacturing: "Local",
		  in_progress: 130,
		  returned: 7,
		  with_shipping_companies: 2900,
		  sold_pieces: 1000,
		  on_shelf: 480,
		  status: "Active",
		  action: "",
		},
		{
		  id: 7,
		  name: "Smartwatch Pro",
		  sku_code: "SKU1007",
		  wholesale_price: "180.00 USD",
		  categories: "Electronics",
		  manufacturing: "International",
		  in_progress: 110,
		  returned: 9,
		  with_shipping_companies: 3300,
		  sold_pieces: 1150,
		  on_shelf: 550,
		  status: "Available",
		  action: "",
		},
		{
		  id: 8,
		  name: "Formal Shoes",
		  sku_code: "SKU1008",
		  wholesale_price: "85.50 USD",
		  categories: "Clothing",
		  manufacturing: "Local",
		  in_progress: 140,
		  returned: 4,
		  with_shipping_companies: 2600,
		  sold_pieces: 800,
		  on_shelf: 420,
		  status: "Processing",
		  action: "",
		},
		{
		  id: 9,
		  name: "Backpack Classic",
		  sku_code: "SKU1009",
		  wholesale_price: "55.99 USD",
		  categories: "Accessories",
		  manufacturing: "International",
		  in_progress: 160,
		  returned: 5,
		  with_shipping_companies: 3400,
		  sold_pieces: 1250,
		  on_shelf: 600,
		  status: "Processing",
		  action: "",
		},
		{
		  id: 10,
		  name: "Winter Gloves",
		  sku_code: "SKU1010",
		  wholesale_price: "30.00 USD",
		  categories: "Clothing",
		  manufacturing: "Local",
		  in_progress: 50,
		  returned: 1,
		  with_shipping_companies: 1800,
		  sold_pieces: 450,
		  on_shelf: 200,
		  status: "Available",
		  action: "",
		},
		{
		  id: 11,
		  name: "Electric Kettle",
		  sku_code: "SKU1011",
		  wholesale_price: "40.99 USD",
		  categories: "Home",
		  manufacturing: "International",
		  in_progress: 70,
		  returned: 2,
		  with_shipping_companies: 2100,
		  sold_pieces: 550,
		  on_shelf: 280,
		  status: "Active",
		  action: "",
		},
		{
		  id: 12,
		  name: "Yoga Mat",
		  sku_code: "SKU1012",
		  wholesale_price: "25.50 USD",
		  categories: "Sports",
		  manufacturing: "Local",
		  in_progress: 90,
		  returned: 3,
		  with_shipping_companies: 2400,
		  sold_pieces: 700,
		  on_shelf: 350,
		  status: "Processing",
		  action: "",
		},
		{
		  id: 13,
		  name: "Wireless Keyboard",
		  sku_code: "SKU1013",
		  wholesale_price: "65.00 USD",
		  categories: "Electronics",
		  manufacturing: "International",
		  in_progress: 110,
		  returned: 4,
		  with_shipping_companies: 2700,
		  sold_pieces: 880,
		  on_shelf: 410,
		  status: "Available",
		  action: "",
		},
		{
		  id: 14,
		  name: "Sunglasses Premium",
		  sku_code: "SKU1014",
		  wholesale_price: "120.00 USD",
		  categories: "Accessories",
		  manufacturing: "Local",
		  in_progress: 95,
		  returned: 2,
		  with_shipping_companies: 2300,
		  sold_pieces: 680,
		  on_shelf: 320,
		  status: "Pending",
		  action: "",
		},
		{
		  id: 15,
		  name: "Gaming Chair",
		  sku_code: "SKU1015",
		  wholesale_price: "250.99 USD",
		  categories: "Furniture",
		  manufacturing: "International",
		  in_progress: 130,
		  returned: 6,
		  with_shipping_companies: 3100,
		  sold_pieces: 1050,
		  on_shelf: 480,
		  status: "Available",
		  action: "",
		}
	  ];
	  	  

	const headContent = [
		{ sort : false , name : t("number") },
		{ sort : true , name : t("name") },
		{ sort : true , name : t("sku_code") },
		{ sort : true , name : t("wholesale_price") },
		{ sort : true , name : t("categories") },
		{ sort : true , name : t("manufacturing") },
		{ sort : true , name : t("in_progress") },
		{ sort : true , name : t("returned") },
		{ sort : true , name : t("with_shipping_companies") },
		{ sort : true , name : t("sold_pieces") },
		{ sort : true , name : t("on_shelf") },
		{ sort : true , name : t("status") },
		{ sort : false , name : t("action") },
	]



	return {headContent , productsData}
}
